FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir fastapi uvicorn
EXPOSE 8000
CMD ["python", "C:\Users\I551674\Desktop\5. Semester\NLP\Multi-Agent-Frontend-Dev\sandbox\backend\4e761a17-43ca-41b2-8dd5-bc837a570135.py"]
